/*
 * Auto-generated Matter Pairing Configuration
 * Generated by: scripts/generate_pairing_config.py
 *
 * QR Code:     MT:-24J0S0.030UU741J00
 * Manual Code: 03351114471
 *
 * To regenerate: make generate-pairing
 */

#pragma once

/* Commissioning Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0x2A3
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 23708391

/* SPAKE2+ Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER \
    "N3FxwiQZKN2nntZikYJZoLSQ+23zIh5JIGSX+I/4tZEEDV2ezlng2z3awwFPBF9si+" \
    "HkAlZFxFPv20Uih3ClaGVGC1OyBz6Zp3z4nDRLN2uV584VTccB5SedYKuc+W9qTA=="
