/*
 * Auto-generated Matter Pairing Configuration
 * Generated by: scripts/generate_pairing_config.py
 *
 * QR Code:     MT:-24J042C002.5Y18P10
 * Manual Code: 05688548040
 *
 * To regenerate: make generate-pairing
 */

#pragma once

/* Commissioning Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0x3A0
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 78716469
#define CHIP_DEVICE_CONFIG_MANUAL_PAIRING_CODE "0568-854-8040"

/* SPAKE2+ Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER \
    "G+6bk4a5/Y11a29COf28ILDWgj+JvgnI3MYgaY4z7u0EALmwGY4gGP+0ak0vYWchcV" \
    "l1EzCqoUkOakM3fI8Kb+AkGVyHUVaC+7BgxTDnmX8QUDWdwMPiKfJT2OcEvMs8pw=="
