/*
 * Auto-generated Matter Pairing Configuration
 * Generated by: scripts/generate_pairing_config.py
 *
 * QR Code:     MT:Y.K9042C00KA0648G00
 * Manual Code: 34970112332
 *
 * *** PLACEHOLDER — run  make generate-pairing  to create your own unique codes ***
 *
 * To regenerate: make generate-pairing
 */

#pragma once

/* Commissioning Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0xF00
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021

/* SPAKE2+ Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER \
    "uWFwqugDNGiEck/po7KHwwMwwqZgN10XuyBajPGuyzUEV/iree4lOrao5GuwnlQ65CJzbeUB49s31EH" \
    "+NEkg0JVI5MGCQGMMT/SRPFNRODm3wH/MYXOrAIs68kOcZpnRFe3//CS3oF10D2a9By0oBii4ZHyj" \
    "tnS4AvF0E3Fzmkvg="
