#!/usr/bin/env python3
"""
svg2icon.py — Convert SVG icons to 1-bit C byte arrays for e-ink display.

Usage:
    python3 tools/svg2icon.py icons/lightbulb.svg icons/fan.svg -o main/icons.h

Each SVG is rendered to ICON_SIZE x ICON_SIZE, thresholded to 1-bit (black/white),
and packed MSB-first into a byte array (BYTES_PER_ROW bytes per row).

Output is a single C header with one array per icon plus a lookup index.
"""

import argparse
import io
import os
import sys

ICON_SIZE = 78
BYTES_PER_ROW = (ICON_SIZE + 7) // 8  # = 10
BYTES_PER_ICON = BYTES_PER_ROW * ICON_SIZE  # = 780
THRESHOLD = 128  # pixels darker than this become black (1), lighter become white (0)


def svg_to_bits(svg_path: str) -> list[int]:
    """Render SVG to ICON_SIZE x ICON_SIZE and return list of 780 bytes (1bpp, MSB first)."""
    try:
        import cairosvg
    except ImportError:
        sys.exit("Error: cairosvg not installed. Run: pip install cairosvg")
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Error: Pillow not installed. Run: pip install pillow")

    # Render SVG → PNG bytes at target size
    png_bytes = cairosvg.svg2png(
        url=svg_path,
        output_width=ICON_SIZE,
        output_height=ICON_SIZE,
    )

    # Open PNG, convert to greyscale, threshold
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")

    # Composite onto white background (handles transparency in icon SVGs)
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    grey = bg.convert("L")

    # Pack into bytes MSB first
    result = []
    pixels = grey.load()
    for row in range(ICON_SIZE):
        for col_byte in range(BYTES_PER_ROW):
            byte = 0
            for bit in range(8):
                col = col_byte * 8 + bit
                if col < ICON_SIZE:
                    # Dark pixel = 1 (draw), light pixel = 0 (background)
                    val = 1 if pixels[col, row] < THRESHOLD else 0
                else:
                    val = 0  # padding bits
                byte = (byte << 1) | val
            result.append(byte)

    assert len(result) == BYTES_PER_ICON
    return result


def icon_name_from_path(path: str) -> str:
    """Derive C identifier from filename: 'icons/01_light-bulb.svg' → 'light_bulb'"""
    import re
    base = os.path.splitext(os.path.basename(path))[0]
    base = re.sub(r"^\d+_", "", base)  # strip leading NN_ numeric prefix
    return base.replace("-", "_").replace(" ", "_")


def format_bytes(data: list[int], cols: int = 12) -> str:
    """Format byte list as C hex literals, cols per line."""
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk))
    return ",\n".join(lines)


def generate_header(icons: dict[str, list[int]]) -> str:
    parts = [
        "// AUTO-GENERATED by tools/svg2icon.py — do not edit by hand",
        "// Icon size: {}x{} px, {} bytes per icon (1bpp, MSB first)".format(
            ICON_SIZE, ICON_SIZE, BYTES_PER_ICON),
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]

    names = list(icons.keys())

    for name, data in icons.items():
        parts.append(f"// {name} ({ICON_SIZE}x{ICON_SIZE}, {BYTES_PER_ICON} bytes)")
        parts.append(f"static const uint8_t icon_{name}[] = {{")
        parts.append(format_bytes(data))
        parts.append("};")
        parts.append("")

    parts.append(f"#define ICON_COUNT {len(names)}")
    parts.append("")
    ptrs = ", ".join(f"icon_{n}" for n in names)
    parts.append(f"static const uint8_t *const icon_list[ICON_COUNT] = {{ {ptrs} }};")
    strs = ", ".join(f'"{n}"' for n in names)
    parts.append(f"static const char *const icon_names[ICON_COUNT] = {{ {strs} }};")
    parts.append("")

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Convert SVG icons to 1-bit C header")
    parser.add_argument("svgs", nargs="+", metavar="SVG", help="Input SVG files")
    parser.add_argument("-o", "--output", required=True, metavar="HEADER",
                        help="Output C header file (e.g. main/icons.h)")
    args = parser.parse_args()

    icons = {}
    for svg_path in args.svgs:
        name = icon_name_from_path(svg_path)
        print(f"  {svg_path} → icon_{name} ({BYTES_PER_ICON} bytes)", flush=True)
        icons[name] = svg_to_bits(svg_path)

    header = generate_header(icons)
    with open(args.output, "w") as f:
        f.write(header)

    print(f"Written: {args.output} ({len(icons)} icon(s), {len(icons) * BYTES_PER_ICON} bytes total)")


if __name__ == "__main__":
    main()
